# Generated by Django 3.0.11 on 2021-03-05 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yara',
            name='id',
        ),
        migrations.AlterField(
            model_name='yara',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
