# Generated by Django 3.0.11 on 2021-03-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210305_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yara',
            old_name='uuid',
            new_name='id',
        ),
    ]
