# Generated by Django 3.2.4 on 2021-11-24 15:34

import bazaar.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20210305_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yara',
            name='content',
            field=models.TextField(help_text='Paste the content of your Yara rule', validators=[bazaar.core.models.check_yara_rule]),
        ),
        migrations.AlterField(
            model_name='yara',
            name='title',
            field=models.CharField(help_text='The fancy name of your Yara rule', max_length=256),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
