# Generated by Django 3.2.4 on 2022-04-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211124_1534'),
        ('core', '0005_auto_20220125_1346'),
    ]

    operations = [
    ]
