# Generated by Django 6.0.1 on 2026-02-17 10:46

import bazaar.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20220125_1346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yara",
            name="content",
            field=models.TextField(
                help_text="Paste the content of your Yara rule",
                validators=[bazaar.core.models.check_yara_rule],
            ),
        ),
        migrations.AlterField(
            model_name="yara",
            name="title",
            field=models.CharField(
                help_text="The fancy name of your Yara rule", max_length=256
            ),
        ),
    ]
