# Generated by Django 6.0.1 on 2026-02-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_set_site_domain_and_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ["domain"],
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
